### ISSUE TITLE
Enhancing Docker container

### ISSUE THREAD

**Issue by PaulSec** [CIRCL/AIL-framework#180]
Hey there, 

I was thinking that would be great to start using Docker Compose to spin up an AIL docker instance. It would also be really cool to spin up the Redis in another instance than from the main one. 

Basically, the Docker compose (in yaml format)would like something like: 

```
version: '3'
services:
  web:
    build: .
    ports:
     - "80:5000"
  redis:
    image: "redis:alpine"
```

It would: 
 - Build it from the Dockerfile in the current repository
- Expose the internal port 5000 (Flask) on the port 80 for example and another container for the Redis would be spinned up. 

Happy to chat about that if you'd like to work together on that :-)
